package com.yuchengtech.bcrm.product.service;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import com.yuchengtech.bcrm.product.model.OcrmFPdProdInfo;
import com.yuchengtech.bob.common.CommonService;
import com.yuchengtech.bob.common.JPABaseDAO;
import com.yuchengtech.bob.vo.AuthUser;

/**
 * @describtion: autogenerated by lhqheli's Tools
 *
 * @author : lhqheli (email: lhqheli@gmail.com)
 * @date : 2014-04-30 10:21:21
 */
@Service
public class ProdInfoService extends CommonService {
    public ProdInfoService(){
        JPABaseDAO<OcrmFPdProdInfo, Long> baseDao = new JPABaseDAO<OcrmFPdProdInfo, Long>(OcrmFPdProdInfo.class);
        super.setBaseDAO(baseDao);
    }
    
    /**
     * create or update prodInfo
     */
    public Object save(Object obj) {
        OcrmFPdProdInfo prodInfo = (OcrmFPdProdInfo)obj;
        if(prodInfo.getProductId() == null){
			AuthUser auth = (AuthUser) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
			prodInfo.setProdCreator(auth.getUserId());
			prodInfo.setCreateDate(new Date());
		}
        return super.save(prodInfo);
    }
    
    /**
     * bacth delete prodInfo
     */
    public void batchRemove(String ids) {
        Map<String, Object> values = new HashMap<String, Object>();
        super.batchUpdateByName("DELETE FROM OcrmFPdProdInfo t WHERE t.id IN("+ ids +")", values);
    }
}
