package com.yuchengtech.emp.ecif.transaction.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-12-22T11:12:55.582+08:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://server.ws.interfaces.mdm.ytec.com/", name = "TxDealWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface TxDealWebService {

//    @WebResult(name = "return", targetNamespace = "")
//    @RequestWrapper(localName = "execute", targetNamespace = "http://server.ws.interfaces.mdm.ytec.com/", className = "com.ytec.mdm.interfaces.ws.server.Execute")
//    @WebMethod
//    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://server.ws.interfaces.mdm.ytec.com/", className = "com.ytec.mdm.interfaces.ws.server.ExecuteResponse")

	  @WebResult(name = "return", targetNamespace = "")
	  @RequestWrapper(localName = "execute", targetNamespace = "http://server.ws.interfaces.mdm.ytec.com/", className = "com.yuchengtech.emp.ecif.transaction.server.Execute")
	  @WebMethod
	  @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://server.ws.interfaces.mdm.ytec.com/", className = "com.yuchengtech.emp.ecif.transaction.server.ExecuteResponse")
    public java.lang.String execute(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
