package com.yuchengtech.emp.ecif.transaction.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-12-22T11:12:55.582+08:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "txDealWebService", 
                  wsdlLocation = "http://localhost:9000/txDealWebService?wsdl",
                  targetNamespace = "http://server.ws.interfaces.mdm.ytec.com/") 
public class TxDealWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.ws.interfaces.mdm.ytec.com/", "txDealWebService");
    public final static QName TxDealWebServiceImplPort = new QName("http://server.ws.interfaces.mdm.ytec.com/", "TxDealWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9000/txDealWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TxDealWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9000/txDealWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TxDealWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TxDealWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TxDealWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TxDealWebService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TxDealWebService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TxDealWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns TxDealWebService
     */
    @WebEndpoint(name = "TxDealWebServiceImplPort")
    public TxDealWebService getTxDealWebServiceImplPort() {
        return super.getPort(TxDealWebServiceImplPort, TxDealWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TxDealWebService
     */
    @WebEndpoint(name = "TxDealWebServiceImplPort")
    public TxDealWebService getTxDealWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TxDealWebServiceImplPort, TxDealWebService.class, features);
    }

}
