package com.yuchengtech.bcrm.finService.model;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
/**
 * @describtion: autogenerated by lhqheli's Tools
 *
 * @author : lhqheli (email: lhqheli@gmail.com)
 * @date : 2014-07-24 13:45:29
 */
@Entity
@Table(name="OCRM_F_FIN_TEMPLATE")
public class OcrmFFinTemplate implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @Id
    @SequenceGenerator(name="OCRM_F_FIN_TEMPLATE_GENERATOR", sequenceName="ID_SEQUENCE", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="OCRM_F_FIN_TEMPLATE_GENERATOR")
    @Column(name="ID")
    private Long id;

    @Column(name="PROD_TYPE")
    private String prodType;

    @Column(name="PROD_RATE")
    private BigDecimal prodRate;

    @Column(name="RISK_TYPE")
    private String riskType;


    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public String getProdType(){
        return this.prodType;
    }

    public void setProdType(String prodType){
        this.prodType = prodType;
    }

    public BigDecimal getProdRate(){
        return this.prodRate;
    }

    public void setProdRate(BigDecimal prodRate){
        this.prodRate = prodRate;
    }

    public String getRiskType(){
        return this.riskType;
    }

    public void setRiskType(String riskType){
        this.riskType = riskType;
    }


}
