package com.yuchengtech.bcrm.wealthManager.model;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
/**
 * @describtion: autogenerated by lhqheli's Tools
 *
 * @author : lhqheli (email: lhqheli@gmail.com)
 * @date : 2014-06-19 17:36:39
 */
@Entity
@Table(name="OCRM_F_FIN_CUST_RISK_QA")
public class OcrmFFinCustRiskQa implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @Id
    @SequenceGenerator(name="OCRM_F_FIN_CUST_RISK_QA_GENERATOR", sequenceName="ID_SEQUENCE", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="OCRM_F_FIN_CUST_RISK_QA_GENERATOR")
    @Column(name="CUST_Q_T_ID")
    private Long custQTId;

    @Column(name="CUST_Q_ID")
    private Long custQId;

    @Column(name="QA_TITLE")
    private String qaTitle;

    @Column(name="CUST_SELECT_CONTENT")
    private String custSelectContent;

    @Column(name="SCORING")
    private BigDecimal scoring;

    @Column(name="TITLE_REMARK")
    private String titleRemark;


    public Long getCustQTId(){
        return this.custQTId;
    }

    public void setCustQTId(Long custQTId){
        this.custQTId = custQTId;
    }

    public Long getCustQId(){
        return this.custQId;
    }

    public void setCustQId(Long custQId){
        this.custQId = custQId;
    }

    public String getQaTitle(){
        return this.qaTitle;
    }

    public void setQaTitle(String qaTitle){
        this.qaTitle = qaTitle;
    }

    public String getCustSelectContent(){
        return this.custSelectContent;
    }

    public void setCustSelectContent(String custSelectContent){
        this.custSelectContent = custSelectContent;
    }

    public BigDecimal getScoring(){
        return this.scoring;
    }

    public void setScoring(BigDecimal scoring){
        this.scoring = scoring;
    }

    public String getTitleRemark(){
        return this.titleRemark;
    }

    public void setTitleRemark(String titleRemark){
        this.titleRemark = titleRemark;
    }


}
