package com.yuchengtech.bcrm.wealthManager.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * @describtion: autogenerated by lhqheli's Tools
 *
 * @author : lhqheli (email: lhqheli@gmail.com)
 * @date : 2014-06-24 16:01:45
 */
@Entity
@Table(name="OCRM_F_FIN_RISK_PARAM_APPR")
public class OcrmFFinRiskParamAppr implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @Id
    @SequenceGenerator(name="OCRM_F_FIN_RISK_PARAM_APPR_GENERATOR", sequenceName="ID_SEQUENCE", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="OCRM_F_FIN_RISK_PARAM_APPR_GENERATOR")
    @Column(name="ID")
    private Long id;

    @Column(name="APPR_STATUS")
    private String apprStatus;

    @Column(name="APPLY_USER")
    private String applyUser;

    @Temporal(TemporalType.DATE)
    @Column(name="APPLY_DATE")
    private Date applyDate;

    @Column(name="APPROVE_USER")
    private String approveUser;

    @Temporal(TemporalType.DATE)
    @Column(name="APPROVE_DATE")
    private Date approveDate;


    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public String getApprStatus(){
        return this.apprStatus;
    }

    public void setApprStatus(String apprStatus){
        this.apprStatus = apprStatus;
    }

    public String getApplyUser(){
        return this.applyUser;
    }

    public void setApplyUser(String applyUser){
        this.applyUser = applyUser;
    }

    public Date getApplyDate(){
        return this.applyDate;
    }

    public void setApplyDate(Date applyDate){
        this.applyDate = applyDate;
    }

    public String getApproveUser(){
        return this.approveUser;
    }

    public void setApproveUser(String approveUser){
        this.approveUser = approveUser;
    }

    public Date getApproveDate(){
        return this.approveDate;
    }

    public void setApproveDate(Date approveDate){
        this.approveDate = approveDate;
    }


}
