package com.yuchengtech.bcrm.wealthManager.model;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
/**
 * @describtion: autogenerated by lhqheli's Tools
 *
 * @author : lhqheli (email: lhqheli@gmail.com)
 * @date : 2014-06-24 16:01:07
 */
@Entity
@Table(name="OCRM_F_FIN_RISK_PARAM")
public class OcrmFFinRiskParam implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @Id
    @SequenceGenerator(name="OCRM_F_FIN_RISK_PARAM_GENERATOR", sequenceName="ID_SEQUENCE", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="OCRM_F_FIN_RISK_PARAM_GENERATOR")
    @Column(name="ID")
    private Long id;

    @Column(name="RISK_CHARACT")
    private String riskCharact;

    @Column(name="LOWER_VALUE")
    private BigDecimal lowerValue;

    @Column(name="UPPER_VALUE")
    private BigDecimal upperValue;

    @Column(name="REMARK")
    private String remark;


    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public String getRiskCharact(){
        return this.riskCharact;
    }

    public void setRiskCharact(String riskCharact){
        this.riskCharact = riskCharact;
    }

    public BigDecimal getLowerValue(){
        return this.lowerValue;
    }

    public void setLowerValue(BigDecimal lowerValue){
        this.lowerValue = lowerValue;
    }

    public BigDecimal getUpperValue(){
        return this.upperValue;
    }

    public void setUpperValue(BigDecimal upperValue){
        this.upperValue = upperValue;
    }

    public String getRemark(){
        return this.remark;
    }

    public void setRemark(String remark){
        this.remark = remark;
    }


}
