package com.yuchengtech.bcrm.wealthManager.model;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
/**
 * @describtion: autogenerated by lhqheli's Tools
 *
 * @author : lhqheli (email: lhqheli@gmail.com)
 * @date : 2014-06-24 16:01:28
 */
@Entity
@Table(name="OCRM_F_FIN_RISK_PARAM_HIS")
public class OcrmFFinRiskParamHis implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @Id
    @SequenceGenerator(name="OCRM_F_FIN_RISK_PARAM_HIS_GENERATOR", sequenceName="ID_SEQUENCE", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="OCRM_F_FIN_RISK_PARAM_HIS_GENERATOR")
    @Column(name="ID")
    private Long id;

    @Column(name="APPR_ID")
    private String apprId;

    @Column(name="RISK_CHARACT")
    private String riskCharact;

    @Column(name="LOWER_VALUE")
    private BigDecimal lowerValue;

    @Column(name="UPPER_VALUE")
    private BigDecimal upperValue;

    @Column(name="IS_BEFORE")
    private String isBefore;
    
    @Column(name="REMARK")
    private String remark;


    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public String getApprId(){
        return this.apprId;
    }

    public void setApprId(String apprId){
        this.apprId = apprId;
    }

    public String getRiskCharact(){
        return this.riskCharact;
    }

    public void setRiskCharact(String riskCharact){
        this.riskCharact = riskCharact;
    }

    public BigDecimal getLowerValue(){
        return this.lowerValue;
    }

    public void setLowerValue(BigDecimal lowerValue){
        this.lowerValue = lowerValue;
    }

    public BigDecimal getUpperValue(){
        return this.upperValue;
    }

    public void setUpperValue(BigDecimal upperValue){
        this.upperValue = upperValue;
    }

    public String getIsBefore(){
        return this.isBefore;
    }

    public void setIsBefore(String isBefore){
        this.isBefore = isBefore;
    }

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}


}
