/**
 * @description 富邦华一银行个人账户新增/变更/销户申请书  打印预览
 * @author denghj1
 * @since 2015-12-2
 */
 Ext.onReady(function(){

	 var html = '<div class="showPrintContent">';
	 	html += '<div class="Noprint"><input type="button" class="button" value="打印" onclick="printPageCurr();"><div id="beforeEnd"></div></div>';
	 	html += '<table class="print_tab_01" id="myTab">';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="titleDiv">富邦华一银行个人账户新增/变更/销户申请书</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">户名：'+CUST_NAME+'</td><td colspan=3 width=330 class="tdDiv">证件种类：'+IDENT_TYPE+'</td><td colspan=3 width=330 class="tdDiv">证件号：'+IDENT_NO+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="td1Div">A 快速关户</td><td colspan=6 width=660 class="tdDiv"><input type="checkbox" name="quick_closed" onclick="return false"/>关闭本人所有账户并销户，同时关闭所有已开通服务</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="td1Div">B 客户信息变更</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">姓名拼音：'+PINYIN_NAME+'</td><td colspan=3 width=330 class="tdDiv">性别：'+GENDER+'</td><td colspan=3 width=330 class="tdDiv">证件有效期：'+IDENT_EXPIRED_DATE+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">出生日期：'+BIRTHDAY+'</td><td colspan=3 width=330 class="tdDiv">国籍：'+CITIZENSHIP+'</td><td colspan=3 width=330 class="tdDiv">出生地：'+BIRTHLOCALE+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">移动电话：'+MOBILE_PHONE+'</td><td colspan=6 width=660 class="tdDiv">（此电话将用于接收短信交易认证码和账务变动通知，仅限大陆和台湾手机）</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=1 width=110 class="tdDiv">电话1</td><td colspan=3 width=330 class="tdDiv">电话类型：'+CONTMETH_TYPE_1+'</td><td colspan=5 width=550 class="tdDiv">电话号码：'+CONTMETH_INFO_SJ+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=1 width=110 class="tdDiv">电话2</td><td colspan=3 width=330 class="tdDiv">电话类型：'+CONTMETH_TYPE_2+'</td><td colspan=5 width=550 class="tdDiv">电话号码：'+CONTMETH_INFO_YD+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="tdDiv">（电话类型包括：住宅电话、办公电话、传真交易核对电话、其他电话）</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=6 width=660 class="tdDiv">居住地址：<input type="text" name="home_addr" value="'+HOME_ADDR+'" style="border:0px;width:450px;height:35px" readOnly="true"/><input type="checkbox" name="home_style" '+(HOME_STYLE == 1 ? "checked":"")+'   onclick="return false"/>租赁<input type="checkbox" name="home_style" '+(HOME_STYLE == 2 ? "checked":"")+' onclick="return false"/>自有</td><td colspan=3 width=330 class="tdDiv">居住地邮编：'+HOME_ZIPCODE+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=6 width=660 class="tdDiv">邮寄地址：'+POST_ADDR+'</td><td colspan=3 width=330 class="tdDiv">邮件邮编：'+POST_ZIPCODE+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="tdDiv">E-mail：<input type="text" value="'+EMAIL+'" name="email" style="border:0px;width:600px;height:35px" readOnly="true"/><input type="checkbox" name="IF_UPDATE_MAIL"  '+(IF_UPDATE_MAIL == "on" ? "checked":"")+' onclick="return false"/>同步更新为电子对账单接收E-mail</td></tr>';
	 	html += '<tr class="tr3Div"><td colspan=9 width=990 class="tdDiv"><br>职业资料</br>';
	 	html += '<br><input type="checkbox" '+(PROFESSION_STYLE == 1 ? "checked":"")+' onclick="return false"/>全员制雇员&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="profession_data" '+(PROFESSION_STYLE == 2 ? "checked":"")+' onclick="return false"/>自雇&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="profession_data" '+(PROFESSION_STYLE == 3 ? "checked":"")+' onclick="return false"/>退休&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="profession_data" '+(PROFESSION_STYLE == 4 ? "checked":"")+' onclick="return false"/>其他（请具体注明）'+PROFESSION_STYLE_REMARK+'</br>';
	 	html += '<br>单位名称：<input type:"text" name="company_name" value="'+UNIT_NAME+'" style="border:0px;width:360px;height:35px" readOnly="true"/>职位：'+DUTY+'</br></td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="tdDiv">是否为美国纳税人：<input type="checkbox" name="usa_tax_flag" '+(USA_TAX_FLAG == 'N' ? "checked":"")+' onclick="return false"/>否&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="usa_tax_flag" '+(USA_TAX_FLAG == 'Y' ? "checked":"")+' onclick="return false"/>是&nbsp;&nbsp;&nbsp;&nbsp;（US TIN/SSN:<input type="text" name="usa_tax_iden_no" value="'+USA_TAX_IDEN_NO+'" style="border:0px;width:240px;height:35px" readOnly="true"/>）</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="tdDiv">是否在我行有关联人：<input type="checkbox" name="cus_bank_rel" '+(IS_RELATED_BANK == 'N' ? "checked":"")+' onclick="return false"/>否&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="cus_bank_rel" '+(IS_RELATED_BANK == 'Y' ? "checked":"")+' onclick="return false"/>是</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="td1Div">C 账户变更（开通和关闭个别账户）</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="td1Div">境内客户：</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">一般综合账户</td><td colspan=6 width=660 class="tdDiv"><input type="checkbox" '+(JN_YBZH == 1 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(JN_YBZH == 0 ? "checked":"")+' onclick="return false"/>关闭&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;账号：'+JN_YBZH_ZH+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">外汇结算户</td><td colspan=6 width=660 class="tdDiv"><input type="checkbox" '+(JN_WHJS == 2 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(JN_WHJS == 0 ? "checked":"")+' onclick="return false"/>关闭&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;账号：'+JN_WHJS_ZH+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">外汇资本金户</td><td colspan=6 width=660 class="tdDiv"><input type="checkbox" '+(JN_WHZB == 3 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(JN_WHZB == 0 ? "checked":"")+' onclick="return false"/>关闭&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;账号：'+JN_WHZB_ZH+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">外汇境内资本变现账户</td><td colspan=6 width=660 class="tdDiv"><input type="checkbox" '+(JN_WHBX == 4 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(JN_WHBX == 0 ? "checked":"")+' onclick="return false"/>关闭&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;账号：'+JN_WHBX_ZH+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="td1Div">境外客户：</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">一般综合账户</td><td colspan=6 width=660 class="tdDiv"><input type="checkbox" '+(JW_YBZH == 5 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(JW_YBZH == 0 ? "checked":"")+' onclick="return false"/>关闭&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;账号：'+JW_YBZH_ZH+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">外汇结算户</td><td colspan=6 width=660 class="tdDiv"><input type="checkbox" '+(JW_WHJS == 6 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(JW_WHJS == 0 ? "checked":"")+' onclick="return false"/>关闭&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;账号：'+JW_WHJS_ZH+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">外汇资本金户</td><td colspan=6 width=660 class="tdDiv"><input type="checkbox" '+(JW_WHZB == 7 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(JW_WHZB == 0 ? "checked":"")+' onclick="return false"/>关闭&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;账号：'+JW_WHZB_ZH+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">港澳居民人民币储蓄账户</td><td colspan=6 width=660 class="tdDiv"><input type="checkbox" '+(JW_GARMB == 8 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(JW_GARMB == 0 ? "checked":"")+' onclick="return false"/>关闭&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;账号：'+JW_GARMB_ZH+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">人民币前期费用专用结算账户</td><td colspan=6 width=660 class="tdDiv"><input type="checkbox" '+(JW_RMBFY == 9 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(JW_RMBFY == 0 ? "checked":"")+' onclick="return false"/>关闭	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;账号：'+JW_RMBFY_ZH+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">人民币再投资专用结算账户</td><td colspan=6 width=660 class="tdDiv"><input type="checkbox" '+(JW_RMBTZ == 10 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(JW_RMBTZ == 0 ? "checked":"")+' onclick="return false"/>关闭&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;账号：'+JW_RMBTZ_ZH+'</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="td1Div">D 服务信息变更</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="td1Div">1.电子银行服务-网络银行</td><td colspan=2 width=220 class="tdDiv"><input type="checkbox" '+(IS_NT_BANK == 1 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(IS_NT_BANK == 0 ? "checked":"")+' onclick="return false"/>关闭</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="tdDiv">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(UKEY == "on" ? "checked":"")+' onclick="return false"/>U-key认证</td><td colspan=2 width=220 rowspan=2 class="tdDiv"><input type="checkbox" '+(ID_CZ1 == "true" ? "checked":"")+' onclick="return false"/>重新设置</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="tdDiv">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(MESSAGE_CODE == "on" ? "checked":"")+' onclick="return false"/>短信认证码（汇款限额RMB50，000元）</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="tdDiv">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(UKEY_LOST == "on" ? "checked":"")+' onclick="return false"/>U-key挂失</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="td1Div">2.电子银行服务-手机银行</td><td colspan=2 width=220 class="tdDiv"><input type="checkbox" '+(MOBILE_BANKING == 40 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(MOBILE_BANKING == 0 ? "checked":"")+' onclick="return false"/>关闭</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="tdDiv">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(MOBILE_BANKING_QUERY == "on" ? "checked":"")+' onclick="return false"/>查询</td><td colspan=2 width=220 rowspan=2 class="tdDiv"><input type="checkbox" '+(ID_CZ2 == "true" ? "checked":"")+' onclick="return false"/>重新设置</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="tdDiv">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(MOBILE_BANKING_TRADE == "on" ? "checked":"")+' onclick="return false"/>交易</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="td1Div">3.电子银行服务-电话银行</td><td colspan=2 width=220 class="tdDiv"><input type="checkbox" '+(PHONE_BANKING == 38 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(PHONE_BANKING == 0 ? "checked":"")+' onclick="return false"/>关闭</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="td1Div">4.传真交易服务（*同时默认开通电子对账单服务，请填写电子对账单服务）</td><td colspan=2 width=220 class="tdDiv"><input type="checkbox" '+(TRANSACTION_SERVICE == 60 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(TRANSACTION_SERVICE == 0 ? "checked":"")+' onclick="return false"/>关闭</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="tdDiv">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;传真机号：'+FAX_NUMBER+'</td><td colspan=2 width=220 class="tdDiv"><input type="checkbox" '+(ID_CZ4 == "true" ? "checked":"")+' onclick="return false"/>重新设置</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="td1Div">5.电子对账单</td><td colspan=2 width=220 class="tdDiv"><input type="checkbox" '+(STATEMENTS == 50 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(STATEMENTS == 0 ? "checked":"")+' onclick="return false"/>关闭</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="tdDiv">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;E-mail:(<input type="checkbox" '+(MAIL_ADDRESS == "on" ? "checked":"")+' onclick="return false"/>同电邮地址） '+MAIL+'</td><td colspan=2 width=220 class="tdDiv"><input type="checkbox" '+(ID_CZ5 == "true" ? "checked":"")+' onclick="return false"/>重新设置</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=7 width=770 class="td1Div">6.账务变动通知</td><td colspan=2 width=220 class="tdDiv"><input type="checkbox" '+(CHANGE_NOTICE == 65 ? "checked":"")+' onclick="return false"/>开通&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" '+(CHANGE_NOTICE == 0 ? "checked":"")+' onclick="return false"/>关闭</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="td1Div">E 密码重置</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="tdDiv">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="" onclick="return false"/>账户密码&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="" onclick="return false"/>网络/手机银行密码&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="" onclick="return false"/>电话银行密码</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="td1Div">F 户名变更</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="tdDiv"><input type="checkbox" name="" onclick="return false"/>兹因变更姓名，本人拟将在贵行所开立之户名称予以更改如下</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=3 width=330 class="tdDiv">旧户名：</td><td colspan=3 width=330 class="tdDiv">新户名：</td><td colspan=3 width=330 class="tdDiv">新户名拼音：</td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990 class="td1Div">G 印鉴新增变更挂失</td></tr>';
	 	html += '<tr class="tr6Div"><td colspan=9 width=990 class="tdDiv"><br><input type="checkbox" name="" onclick="return false"/>兹因新增加账户账号，本人预留新印鉴与之对应。新印鉴自&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;年&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;月&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日起启用。</br>';
	 	html += '<br><input type="checkbox" name="" onclick="return false"/>兹因变更印鉴，请照下列方格内所留之新印鉴更换。新印鉴自&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;年&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;月&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日起启用，原旧印鉴</br>';
	 	html += '<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;约定同时失效。又本存户以前在贵行使用旧印鉴所订立各种契据及担保等文件仍属有效。</br>';
	 	html += '<br><input type="checkbox" name="" onclick="return false"/>兹因本人印鉴不慎遗失，现特向贵行提出印鉴挂失申请，并请照下列方格内所留之新印鉴更换。新印鉴</br>';
	 	html += '<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;自&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;年&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;月&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日起启用，原旧印鉴约定同时失效。又本存户以前在贵行使用旧印鉴所订立各种</br>';
	 	html += '<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;契据及担保等文件仍属有效。</br></td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990><span class="td1Div">新增印鉴样式&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="tdDiv">（对应账号：<input type="text" name="" style="border:0px;width:360px;height:35px" readOnly="true"/>）共&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;式凭&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;式有效&nbsp;&nbsp;</span></td></tr>';
	 	html += '<tr class="tr10Div"><td colspan=4 width=440 class="tdDiv"></td><td colspan=5 width=550 class="tdDiv"></td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990><span class="td1Div">需变更旧印鉴样式&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="tdDiv">（对应账号：<input type="text" name="" style="border:0px;width:360px;height:35px" readOnly="true"/>）</span></td></tr>';
	 	html += '<tr class="tr10Div"><td colspan=4 width=440 class="tdDiv"></td><td colspan=5 width=550 class="tdDiv"></td></tr>';
	 	html += '<tr class="trDiv"><td colspan=9 width=990><span class="td1Div">挂失/变更后新印鉴样式&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="tdDiv">（对应账号：<input type="text" name="" style="border:0px;width:360px;height:35px" readOnly="true"/>）共&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;式凭&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;式有效&nbsp;&nbsp;</span></td></tr>';
	 	html += '<tr class="tr10Div"><td colspan=4 width=440 class="tdDiv"></td><td colspan=5 width=550 class="tdDiv"></td></tr>';
	 	html += '</table>';
	 	html += '</div>';
	 
	 var printPanel = new Ext.Panel({
		 layout : 'fit',
		 autoScroll : true,
		 html : html,
	 });
	 
	 var viewport = new Ext.Viewport({
		 layout:'fit',
		 items:[printPanel]
	 });
 });  