package com.yuchengtech.bcrm.customer.phoneMkt.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * @describtion: autogenerated by lhqheli's Tools
 *
 * @author : lhqheli (email: lhqheli@gmail.com)
 * @date : 2014-02-08 15:32:55
 */
@Entity
@Table(name="OCRM_F_MM_INTERVIEW_MAIN")
public class OcrmFMmInterviewMain implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @Id
    @SequenceGenerator(name="OCRM_F_MM_INTERVIEW_MAIN_GENERATOR", sequenceName="ID_SEQUENCE", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="OCRM_F_MM_INTERVIEW_MAIN_GENERATOR")
    @Column(name="ID")
    private Long id;

    @Column(name="CUST_ID")
    private String custId;

    @Column(name="USER_ID")
    private String userId;

    @Column(name="USER_NAME")
    private String userName;

    @Temporal(TemporalType.DATE)
    @Column(name="INTERVIEW_DATE")
    private Date interviewDate;

    @Column(name="BIS_TYPE")
    private String bisType;

    @Column(name="TEL_TYPE")
    private String telType;

    @Column(name="FOLLOW_DO")
    private String followDo;

    @Column(name="REMARK")
    private String remark;

    @Column(name="PHYSICAL_ADDR")
    private String physicalAddr;

    @Column(name="BIZ_NO")
    private String bizNo;

    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public String getCustId(){
        return this.custId;
    }

    public void setCustId(String custId){
        this.custId = custId;
    }

    public String getUserId(){
        return this.userId;
    }

    public void setUserId(String userId){
        this.userId = userId;
    }

    public String getUserName(){
        return this.userName;
    }

    public void setUserName(String userName){
        this.userName = userName;
    }

    public Date getInterviewDate(){
        return this.interviewDate;
    }

    public void setInterviewDate(Date interviewDate){
        this.interviewDate = interviewDate;
    }

    public String getBisType(){
        return this.bisType;
    }

    public void setBisType(String bisType){
        this.bisType = bisType;
    }

    public String getTelType(){
        return this.telType;
    }

    public void setTelType(String telType){
        this.telType = telType;
    }

    public String getFollowDo(){
        return this.followDo;
    }

    public void setFollowDo(String followDo){
        this.followDo = followDo;
    }

    public String getRemark(){
        return this.remark;
    }

    public void setRemark(String remark){
        this.remark = remark;
    }

    public String getPhysicalAddr(){
        return this.physicalAddr;
    }

    public void setPhysicalAddr(String physicalAddr){
        this.physicalAddr = physicalAddr;
    }

	public String getBizNo() {
		return bizNo;
	}

	public void setBizNo(String bizNo) {
		this.bizNo = bizNo;
	}


}
