package com.yuchengtech.bcrm.sales.marketTask.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * @describtion: autogenerated by lhqheli's Tools
 *
 * @author : lhqheli (email: lhqheli@gmail.com)
 * @date : 2014-07-03 10:21:33
 */
@Entity
@Table(name="OCRM_F_MM_TASK_TARGET")
public class OcrmFMmTaskTarget implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @Id
    @SequenceGenerator(name="OCRM_F_MM_TASK_TARGET_GENERATOR", sequenceName="ID_SEQUENCE", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="OCRM_F_MM_TASK_TARGET_GENERATOR")
    @Column(name="TARGET_NO")
    private Long targetNo;

    @Column(name="TASK_ID")
    private Long taskId;

    @Column(name="TARGET_CODE")
    private String targetCode;

    @Column(name="ORIGINAL_VALUE")
    private BigDecimal originalValue;

    @Column(name="TARGET_VALUE")
    private BigDecimal targetValue;

    @Column(name="ACHIEVE_VALUE")
    private BigDecimal achieveValue;

    @Column(name="ACHIEVE_PERCENT")
    private BigDecimal achievePercent;

    @Column(name="CREATE_USER_ID")
    private String createUserId;

    @Column(name="CREATE_USER_NAME")
    private String createUserName;

    @Column(name="RECENTLY_UPDATE_ID")
    private String recentlyUpdateId;

    @Column(name="RECENTLY_UPDATE_NAME")
    private String recentlyUpdateName;

    @Temporal(TemporalType.DATE)
    @Column(name="RECENTLY_UPDATE_DATE")
    private Date recentlyUpdateDate;
    
    @Column(name="CYCLE_TYPE")
    private String cycleType;
    
    @Column(name="CYCLE_NAME")
    private String cycleName;
    
    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE")
    private Date startDate;
    
    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE")
    private Date endDate;
    
    @Column(name="ACHIEVE_VALUE_STATE")
    private String achieveValueState;
    
    @Column(name="ACHIEVE_REMARK")
    private String achieveRemark;
    
    
    
    

    public String getAchieveRemark() {
		return achieveRemark;
	}

	public void setAchieveRemark(String achieveRemark) {
		this.achieveRemark = achieveRemark;
	}

	public String getAchieveValueState() {
		return achieveValueState;
	}

	public void setAchieveValueState(String achieveValueState) {
		this.achieveValueState = achieveValueState;
	}

	public Long getTargetNo(){
        return this.targetNo;
    }

    public void setTargetNo(Long targetNo){
        this.targetNo = targetNo;
    }

    public Long getTaskId(){
        return this.taskId;
    }

    public void setTaskId(Long taskId){
        this.taskId = taskId;
    }

    public String getTargetCode(){
        return this.targetCode;
    }

    public void setTargetCode(String targetCode){
        this.targetCode = targetCode;
    }

    public BigDecimal getOriginalValue(){
        return this.originalValue;
    }

    public void setOriginalValue(BigDecimal originalValue){
        this.originalValue = originalValue;
    }

    public BigDecimal getTargetValue(){
        return this.targetValue;
    }

    public void setTargetValue(BigDecimal targetValue){
        this.targetValue = targetValue;
    }

    public BigDecimal getAchieveValue(){
        return this.achieveValue;
    }

    public void setAchieveValue(BigDecimal achieveValue){
        this.achieveValue = achieveValue;
    }

    public BigDecimal getAchievePercent(){
        return this.achievePercent;
    }

    public void setAchievePercent(BigDecimal achievePercent){
        this.achievePercent = achievePercent;
    }

    public String getCreateUserId(){
        return this.createUserId;
    }

    public void setCreateUserId(String createUserId){
        this.createUserId = createUserId;
    }

    public String getCreateUserName(){
        return this.createUserName;
    }

    public void setCreateUserName(String createUserName){
        this.createUserName = createUserName;
    }

    public String getRecentlyUpdateId(){
        return this.recentlyUpdateId;
    }

    public void setRecentlyUpdateId(String recentlyUpdateId){
        this.recentlyUpdateId = recentlyUpdateId;
    }

    public String getRecentlyUpdateName(){
        return this.recentlyUpdateName;
    }

    public void setRecentlyUpdateName(String recentlyUpdateName){
        this.recentlyUpdateName = recentlyUpdateName;
    }

    public Date getRecentlyUpdateDate(){
        return this.recentlyUpdateDate;
    }

    public void setRecentlyUpdateDate(Date recentlyUpdateDate){
        this.recentlyUpdateDate = recentlyUpdateDate;
    }

	public String getCycleType() {
		return cycleType;
	}

	public void setCycleType(String cycleType) {
		this.cycleType = cycleType;
	}

	public String getCycleName() {
		return cycleName;
	}

	public void setCycleName(String cycleName) {
		this.cycleName = cycleName;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}


}
